name: PR Verification
on: 
  pull_request:
    branches: ["main"]
    
jobs:
  verify-pr:
    runs-on: ubutu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Print Branch Information
        run: echo "PR check running for branch -> ${{ github.head_ref }}"
          
