name: Secrets Management
on: workflow_dispatch

jobs:
  test-secrets:
    runs-on: ubuntu-latest
    env:
      MY_SECRET_ENV_VAR: ${{ secret.MY_SECRET_MESSAGE }}
    steps:
      - name: verify secret presence
        run: |
          if [ -n "$MY_SECRET_ENV_VAR"]; then
            echo "The secret is set: true"
            else
              echo "The secret is set: false"
          fi

      - name: Accidental Print Test
        run: |
          echo "Direct print attempt: ${{ secrets.MY_SECRET_MESSAGE }}"
