name: App & Src Build

on:
  push:
    branches:
      - main
      - 'release/*'
    paths:
      - 'src/**'
      - 'app/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Triggered because code in src/ or app/ changed on main or a release branch."
